title: "FUJIE"
author: "Blog Author"
description: "Really cool blog about ... something"
more: "read more Â»"
url: ""
baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: true

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "arsly"
  #isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/twitter/"
  - github: "https://github.com/niklasbuschmann/contrast"
  - envelope: "mailto:niklas.buschmann@posteo.de"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]

theme: jekyll-theme-cayman